import type {
  Booking,
  CleaningTask,
  Guest,
  Integration,
  MaintenanceRequest,
  OwnerStatement,
  Property,
  TeamMember,
  Workspace,
} from "./types";

export const workspace: Workspace = {
  id: "ws_demo",
  name: "Apex Property Group",
  plan: "Professional",
  rentalModel: "mixed",
  properties: 45,
  status: "trial",
};

export const currentUser: TeamMember = {
  id: "user_alex",
  name: "Alex Carter",
  email: "alex.carter@propflow.com",
  role: "workspace_admin",
  status: "active",
  avatar:
    "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=256&q=80",
};

export const teamMembers: TeamMember[] = [
  currentUser,
  {
    id: "user_sarah",
    name: "Sarah Jenkins",
    email: "sarah.j@propflow.com",
    role: "manager",
    status: "active",
    avatar:
      "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=256&q=80",
  },
  {
    id: "user_marcus",
    name: "Marcus Chen",
    email: "m.chen@propflow.com",
    role: "maintenance_tech",
    status: "active",
    avatar:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=256&q=80",
  },
  {
    id: "user_elena",
    name: "Elena Rodriguez",
    email: "elena.r@external.com",
    role: "cleaner",
    status: "pending",
  },
];

export const properties: Property[] = [
  {
    id: "villa-azure",
    name: "Villa Azure",
    location: "Miami Beach, FL",
    address: "1240 Ocean Drive, Miami Beach, FL",
    owner: "Sarah Jenkins",
    status: "Occupied",
    occupancy: 95,
    revenueYtd: 142500,
    bedrooms: 4,
    bathrooms: 3.5,
    area: "3,200 sqft",
    rating: 4.96,
    model: "short_term",
    image:
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "pinnacle-penthouse",
    name: "The Pinnacle Penthouse",
    location: "New York, NY",
    address: "88 Hudson Yards, New York, NY",
    owner: "Marcus Vance",
    status: "Cleaning",
    occupancy: 82,
    revenueYtd: 38900,
    bedrooms: 3,
    bathrooms: 2,
    area: "2,100 sqft",
    rating: 4.82,
    model: "short_term",
    image:
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "oakwood-estate",
    name: "Oakwood Estate",
    location: "Austin, TX",
    address: "91 Oak Creek Blvd, Austin, TX",
    owner: "Elena Rostova",
    status: "Vacant",
    occupancy: 60,
    revenueYtd: 29150,
    bedrooms: 5,
    bathrooms: 4,
    area: "4,400 sqft",
    rating: 4.7,
    model: "mixed",
    image:
      "https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "aspen-summit",
    name: "Aspen Summit",
    location: "Aspen, CO",
    address: "42 Ridge Trail, Aspen, CO",
    owner: "The Sterling Group",
    status: "Maintenance",
    occupancy: 88,
    revenueYtd: 24800,
    bedrooms: 6,
    bathrooms: 5,
    area: "5,800 sqft",
    rating: 4.91,
    model: "short_term",
    image:
      "https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "maple-court",
    name: "Maple Court Apartments",
    location: "Denver, CO",
    address: "501 Maple Court, Denver, CO",
    owner: "John Smith",
    status: "Occupied",
    occupancy: 97,
    revenueYtd: 52200,
    bedrooms: 2,
    bathrooms: 2,
    area: "18 units",
    rating: 4.4,
    model: "long_term",
    image:
      "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1200&q=80",
  },
];

export const bookings: Booking[] = [
  {
    id: "bk_001",
    guest: "John Doe",
    email: "john.d@example.com",
    property: "Oceanview Villa",
    stayDates: "Oct 12 - Oct 18",
    nights: 6,
    platform: "Airbnb",
    payment: "Paid",
    status: "Confirmed",
    amount: 4200,
  },
  {
    id: "bk_002",
    guest: "Alice Smith",
    email: "alice.s@example.com",
    property: "Downtown Loft",
    stayDates: "Oct 15 - Oct 17",
    nights: 2,
    platform: "VRBO",
    payment: "Partial",
    status: "Checked-in",
    amount: 1200,
  },
  {
    id: "bk_003",
    guest: "Michael Wong",
    email: "m.wong@example.com",
    property: "Mountain Retreat",
    stayDates: "Oct 10 - Oct 14",
    nights: 4,
    platform: "Direct",
    payment: "Paid",
    status: "Checked-out",
    amount: 3100,
  },
  {
    id: "bk_004",
    guest: "Sarah Jenkins",
    email: "sarah.j@example.com",
    property: "Lakeside Cabin",
    stayDates: "Oct 22 - Oct 29",
    nights: 7,
    platform: "Airbnb",
    payment: "Unpaid",
    status: "Confirmed",
    amount: 5600,
  },
  {
    id: "lease_001",
    guest: "Jordan Miles",
    email: "jordan.miles@example.com",
    property: "Maple Court Apartments",
    stayDates: "Jan 1 - Dec 31",
    nights: 365,
    platform: "Lease",
    payment: "Paid",
    status: "Checked-in",
    amount: 2850,
  },
];

export const guests: Guest[] = [
  {
    id: "guest_001",
    name: "Eleanor Richards",
    email: "eleanor.r@example.com",
    phone: "+1 (555) 019-8472",
    status: "Active Booking",
    stays: 4,
    ltv: 12450,
    lastStay: "Currently in-house - The Azure Villa",
    flag: "VIP",
  },
  {
    id: "guest_002",
    name: "Marcus Rodriguez",
    email: "m.rodriguez@techcorp.com",
    phone: "+1 (555) 234-9910",
    status: "Past Guest",
    stays: 1,
    ltv: 2100,
    lastStay: "Oct 12 - Oct 18, 2023 - Downtown Loft 4B",
    flag: "Corporate Client",
  },
  {
    id: "guest_003",
    name: "David Chen",
    email: "david.chen@email.com",
    phone: "+44 7700 900077",
    status: "Upcoming",
    stays: 2,
    ltv: 4850,
    lastStay: "Starts Nov 5, 2023 - Seaside Cottage",
    flag: "Needs Attention",
  },
  {
    id: "tenant_001",
    name: "Jordan Miles",
    email: "jordan.miles@example.com",
    phone: "+1 (555) 421-5521",
    status: "Tenant",
    stays: 1,
    ltv: 34200,
    lastStay: "Lease through Dec 31 - Maple Court",
  },
];

export const cleaningTasks: CleaningTask[] = [
  {
    id: "clean_001",
    property: "Unit 402, The Azure",
    address: "1250 Ocean Ave, Miami, FL",
    checkIn: "3:00 PM",
    type: "Turnover - Deep Clean",
    status: "pending",
    completed: 0,
    total: 12,
    image:
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "clean_002",
    property: "The Summit Penthouse",
    address: "88 Hudson Yards, New York, NY",
    checkIn: "11:00 AM",
    type: "Active - Standard Reset",
    status: "in_progress",
    completed: 3,
    total: 9,
    image:
      "https://images.unsplash.com/photo-1600607687644-c7171b42498f?auto=format&fit=crop&w=1200&q=80",
  },
];

export const maintenanceRequests: MaintenanceRequest[] = [
  {
    id: "wo_001",
    property: "Oceanview Tower #1204",
    location: "4500 Coastal Highway",
    title: "Major Pipe Burst",
    description:
      "Active leak reported in master bathroom ceiling. Water spreading to hallway.",
    priority: "Critical",
    status: "urgent",
    reportedAgo: "12 mins ago",
    estimate: "TBD",
    assignee: "Unassigned",
  },
  {
    id: "wo_002",
    property: "The Grand Estate #2B",
    location: "1800 Heritage Lane",
    title: "HVAC System Failure",
    description:
      "AC unit blowing warm air, tenant reported 85 degrees indoors.",
    priority: "High Priority",
    status: "urgent",
    reportedAgo: "38 mins ago",
    estimate: "$1,200",
    assignee: "J. Smith",
  },
  {
    id: "wo_003",
    property: "Unit 110 - The Azure",
    location: "Kitchen",
    title: "Dishwasher Replacement",
    description:
      "Old unit removed, currently installing the new Bosch model.",
    priority: "Routine",
    status: "in_progress",
    reportedAgo: "Yesterday",
    estimate: "$850",
    assignee: "S. Davis",
  },
  {
    id: "wo_004",
    property: "88 Oak Creek Blvd",
    location: "Garage",
    title: "Garage Door Motor",
    description: "Motor arriving Oct 24. Install requires two technicians.",
    priority: "Low",
    status: "awaiting_parts",
    reportedAgo: "2 days ago",
    estimate: "$450",
    assignee: "J. Smith",
  },
  {
    id: "wo_005",
    property: "Unit 205 - The Azure",
    location: "Bathroom",
    title: "Leaky Faucet Repair",
    description: "Completed with final cost below estimate.",
    priority: "Routine",
    status: "completed",
    reportedAgo: "Today",
    estimate: "$85",
    assignee: "S. Davis",
  },
];

export const ownerStatements: OwnerStatement[] = [
  {
    id: "stmt_001",
    owner: "Sarah Jenkins",
    properties: 4,
    revenue: 124500,
    expenses: 42160,
    payout: 14250,
    status: "ready",
  },
  {
    id: "stmt_002",
    owner: "The Sterling Group",
    properties: 12,
    revenue: 482000,
    expenses: 111300,
    payout: 68200,
    status: "draft",
  },
  {
    id: "stmt_003",
    owner: "John Smith",
    properties: 18,
    revenue: 342000,
    expenses: 78000,
    payout: 30100,
    status: "sent",
  },
];

export const integrations: Integration[] = [
  {
    id: "int_paypal",
    provider: "paypal",
    name: "PayPal Subscriptions",
    status: "credential_required",
    description: "Plan billing, subscription lifecycle, invoices, and webhooks.",
    lastSync: "Waiting for REST app credentials",
  },
  {
    id: "int_google",
    provider: "google_calendar",
    name: "Google Calendar",
    status: "connected",
    description: "Calendar import, event sync, and operational reminders.",
    lastSync: "12 mins ago",
  },
  {
    id: "int_airbnb",
    provider: "airbnb",
    name: "Airbnb Partner API",
    status: "credential_required",
    description: "Credential-gated channel sync for bookings, listings, and availability.",
    lastSync: "Partner access required",
  },
  {
    id: "int_vrbo",
    provider: "vrbo",
    name: "VRBO Connectivity",
    status: "credential_required",
    description: "Credential-gated channel sync for bookings and availability.",
    lastSync: "Connectivity credentials required",
  },
  {
    id: "int_quickbooks",
    provider: "quickbooks",
    name: "QuickBooks",
    status: "disabled",
    description: "Deferred after CSV exports for owner statements and expenses.",
    lastSync: "Planned for phase 2",
  },
];

export const dashboardMetrics = [
  { label: "Gross Revenue", value: "$142,500", delta: "+12.5% vs last month" },
  { label: "Net Profit", value: "$98,200", delta: "+8.2% vs last month" },
  { label: "Occupancy Rate", value: "88%", delta: "Stable across 45 properties" },
  { label: "Ops Health Score", value: "94/100", delta: "Optimal operational status" },
];

export const platformMetrics = [
  { label: "Total Workspaces", value: "1,248", delta: "+12%" },
  { label: "Active Subs", value: "11,402", delta: "+4.2%" },
  { label: "MRR", value: "$482k", delta: "+8.1%" },
  { label: "Churn Rate", value: "1.2%", delta: "-0.3%" },
];
